from enum import Enum


class UserRole(str, Enum):
    SUPER_ADMIN = "SUPER_ADMIN"
    HOSPITAL_ADMIN = "HOSPITAL_ADMIN"
    RECEPTIONIST = "RECEPTIONIST"
    DOCTOR = "DOCTOR"
    DOCTOR_ASSISTANT = "DOCTOR_ASSISTANT"


class Gender(str, Enum):
    MALE = "MALE"
    FEMALE = "FEMALE"
    OTHER = "OTHER"
    UNSPECIFIED = "UNSPECIFIED"


class QueueStatus(str, Enum):
    OPEN = "OPEN"
    PAUSED = "PAUSED"
    CLOSED = "CLOSED"


class TokenStatus(str, Enum):
    WAITING = "WAITING"
    READY = "READY"
    AWAY = "AWAY"
    RETURNING = "RETURNING"
    CALLED = "CALLED"
    SERVING = "SERVING"
    MISSED = "MISSED"
    SKIPPED = "SKIPPED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    TRANSFERRED = "TRANSFERRED"


class PriorityLevel(str, Enum):
    EMERGENCY = "EMERGENCY"  # Highest priority
    HIGH = "HIGH"            # Elderly, vulnerable, or high-priority cases
    NORMAL = "NORMAL"        # Standard FIFO walk-in queue


class QueueEventType(str, Enum):
    TOKEN_CREATED = "TOKEN_CREATED"
    TOKEN_STATUS_CHANGED = "TOKEN_STATUS_CHANGED"
    TOKEN_CALLED = "TOKEN_CALLED"
    TOKEN_RECALLED = "TOKEN_RECALLED"
    TOKEN_SERVING = "TOKEN_SERVING"
    TOKEN_COMPLETED = "TOKEN_COMPLETED"
    TOKEN_SKIPPED = "TOKEN_SKIPPED"
    TOKEN_MISSED = "TOKEN_MISSED"
    TOKEN_REJOINED = "TOKEN_REJOINED"
    TOKEN_PRIORITY_CHANGED = "TOKEN_PRIORITY_CHANGED"
    TOKEN_AWAY = "TOKEN_AWAY"
    TOKEN_RETURNING = "TOKEN_RETURNING"
    TOKEN_READY = "TOKEN_READY"
    TOKEN_CANCELLED = "TOKEN_CANCELLED"
    TOKEN_TRANSFERRED = "TOKEN_TRANSFERRED"
    QUEUE_OPENED = "QUEUE_OPENED"
    QUEUE_PAUSED = "QUEUE_PAUSED"
    QUEUE_RESUMED = "QUEUE_RESUMED"
    QUEUE_CLOSED = "QUEUE_CLOSED"
